pi_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  wheel1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel1_joint
    pid: {p: 3.0, i: 1, d: 0.0}
  
  wheel2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wheel2_joint
    pid: {p: 3.0, i: 1, d: 0.0}